repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: local
    hooks:
    - id: isort
      name: isort
      entry: poetry run isort --settings-path pyproject.toml
      exclude: ^{{ cookiecutter.project_name }}/
      language: system
      types: [python]

    - id: pyupgrade
      name: pyupgrade
      entry: poetry run pyupgrade --py37-plus
      exclude: ^{{ cookiecutter.project_name }}/
      language: system
      types: [python]

    - id: black
      name: black
      entry: poetry run black --config pyproject.toml
      exclude: ^{{ cookiecutter.project_name }}/
      language: system
      types: [python]

    - id: flakehell
      name: flakehell
      entry: poetry run flakehell lint
      exclude: ^{{ cookiecutter.project_name }}/
      language: system
      types: [python]

    - id: mypy
      name: mypy
      entry: poetry run mypy --config-file pyproject.toml
      exclude: ^{{ cookiecutter.project_name }}/
      language: system
      types: [python]
